// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: donuts/protos/donuts.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Donuts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price  int32   `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Rating float32 `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *Donuts) Reset() {
	*x = Donuts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Donuts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Donuts) ProtoMessage() {}

func (x *Donuts) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Donuts.ProtoReflect.Descriptor instead.
func (*Donuts) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{0}
}

func (x *Donuts) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Donuts) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Donuts) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Donuts) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type DonutsOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Donut *Donuts `protobuf:"bytes,1,opt,name=donut,proto3" json:"donut,omitempty"`
	Count int32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Cost  int32   `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
}

func (x *DonutsOrder) Reset() {
	*x = DonutsOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DonutsOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonutsOrder) ProtoMessage() {}

func (x *DonutsOrder) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonutsOrder.ProtoReflect.Descriptor instead.
func (*DonutsOrder) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{1}
}

func (x *DonutsOrder) GetDonut() *Donuts {
	if x != nil {
		return x.Donut
	}
	return nil
}

func (x *DonutsOrder) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DonutsOrder) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type AreYouOpenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reponse bool `protobuf:"varint,1,opt,name=reponse,proto3" json:"reponse,omitempty"`
}

func (x *AreYouOpenResponse) Reset() {
	*x = AreYouOpenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreYouOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreYouOpenResponse) ProtoMessage() {}

func (x *AreYouOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreYouOpenResponse.ProtoReflect.Descriptor instead.
func (*AreYouOpenResponse) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{2}
}

func (x *AreYouOpenResponse) GetReponse() bool {
	if x != nil {
		return x.Reponse
	}
	return false
}

type AreYouOpenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DayOfTheWeek string `protobuf:"bytes,1,opt,name=dayOfTheWeek,proto3" json:"dayOfTheWeek,omitempty"`
}

func (x *AreYouOpenRequest) Reset() {
	*x = AreYouOpenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreYouOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreYouOpenRequest) ProtoMessage() {}

func (x *AreYouOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreYouOpenRequest.ProtoReflect.Descriptor instead.
func (*AreYouOpenRequest) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{3}
}

func (x *AreYouOpenRequest) GetDayOfTheWeek() string {
	if x != nil {
		return x.DayOfTheWeek
	}
	return ""
}

type CreateDonutsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Donut *Donuts `protobuf:"bytes,1,opt,name=donut,proto3" json:"donut,omitempty"`
	Count int32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CreateDonutsRequest) Reset() {
	*x = CreateDonutsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDonutsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDonutsRequest) ProtoMessage() {}

func (x *CreateDonutsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDonutsRequest.ProtoReflect.Descriptor instead.
func (*CreateDonutsRequest) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDonutsRequest) GetDonut() *Donuts {
	if x != nil {
		return x.Donut
	}
	return nil
}

func (x *CreateDonutsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateDonutsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created bool `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *CreateDonutsResponse) Reset() {
	*x = CreateDonutsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDonutsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDonutsResponse) ProtoMessage() {}

func (x *CreateDonutsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDonutsResponse.ProtoReflect.Descriptor instead.
func (*CreateDonutsResponse) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDonutsResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type GetDonutsListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDonutsListRequest) Reset() {
	*x = GetDonutsListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDonutsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonutsListRequest) ProtoMessage() {}

func (x *GetDonutsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonutsListRequest.ProtoReflect.Descriptor instead.
func (*GetDonutsListRequest) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{6}
}

type GetDonutsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Donuts []*Donuts `protobuf:"bytes,1,rep,name=donuts,proto3" json:"donuts,omitempty"`
}

func (x *GetDonutsListResponse) Reset() {
	*x = GetDonutsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDonutsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonutsListResponse) ProtoMessage() {}

func (x *GetDonutsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonutsListResponse.ProtoReflect.Descriptor instead.
func (*GetDonutsListResponse) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{7}
}

func (x *GetDonutsListResponse) GetDonuts() []*Donuts {
	if x != nil {
		return x.Donuts
	}
	return nil
}

type OrderDonutsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order     []*DonutsOrder `protobuf:"bytes,1,rep,name=order,proto3" json:"order,omitempty"`
	TotalCost int32          `protobuf:"varint,2,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
}

func (x *OrderDonutsRequest) Reset() {
	*x = OrderDonutsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDonutsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDonutsRequest) ProtoMessage() {}

func (x *OrderDonutsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDonutsRequest.ProtoReflect.Descriptor instead.
func (*OrderDonutsRequest) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{8}
}

func (x *OrderDonutsRequest) GetOrder() []*DonutsOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderDonutsRequest) GetTotalCost() int32 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type OrderDonutsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response bool `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *OrderDonutsResponse) Reset() {
	*x = OrderDonutsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDonutsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDonutsResponse) ProtoMessage() {}

func (x *OrderDonutsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDonutsResponse.ProtoReflect.Descriptor instead.
func (*OrderDonutsResponse) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{9}
}

func (x *OrderDonutsResponse) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

type UpdateDonutsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Donut *Donuts `protobuf:"bytes,1,opt,name=donut,proto3" json:"donut,omitempty"`
	Count int32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *UpdateDonutsRequest) Reset() {
	*x = UpdateDonutsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDonutsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDonutsRequest) ProtoMessage() {}

func (x *UpdateDonutsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDonutsRequest.ProtoReflect.Descriptor instead.
func (*UpdateDonutsRequest) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateDonutsRequest) GetDonut() *Donuts {
	if x != nil {
		return x.Donut
	}
	return nil
}

func (x *UpdateDonutsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateDonutsReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reponse bool `protobuf:"varint,1,opt,name=reponse,proto3" json:"reponse,omitempty"`
}

func (x *UpdateDonutsReponse) Reset() {
	*x = UpdateDonutsReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDonutsReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDonutsReponse) ProtoMessage() {}

func (x *UpdateDonutsReponse) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDonutsReponse.ProtoReflect.Descriptor instead.
func (*UpdateDonutsReponse) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateDonutsReponse) GetReponse() bool {
	if x != nil {
		return x.Reponse
	}
	return false
}

type ClearDonutsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DonutIds []string `protobuf:"bytes,1,rep,name=donutIds,proto3" json:"donutIds,omitempty"`
}

func (x *ClearDonutsRequest) Reset() {
	*x = ClearDonutsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearDonutsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearDonutsRequest) ProtoMessage() {}

func (x *ClearDonutsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearDonutsRequest.ProtoReflect.Descriptor instead.
func (*ClearDonutsRequest) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{12}
}

func (x *ClearDonutsRequest) GetDonutIds() []string {
	if x != nil {
		return x.DonutIds
	}
	return nil
}

type ClearDonutsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response bool `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *ClearDonutsResponse) Reset() {
	*x = ClearDonutsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_donuts_protos_donuts_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearDonutsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearDonutsResponse) ProtoMessage() {}

func (x *ClearDonutsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donuts_protos_donuts_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearDonutsResponse.ProtoReflect.Descriptor instead.
func (*ClearDonutsResponse) Descriptor() ([]byte, []int) {
	return file_donuts_protos_donuts_proto_rawDescGZIP(), []int{13}
}

func (x *ClearDonutsResponse) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

var File_donuts_protos_donuts_proto protoreflect.FileDescriptor

var file_donuts_protos_donuts_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f,
	0x6e, 0x75, 0x74, 0x73, 0x22, 0x5a, 0x0a, 0x06, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x22, 0x5d, 0x0a, 0x0b, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x24, 0x0a, 0x05, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x05,
	0x64, 0x6f, 0x6e, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x22,
	0x2e, 0x0a, 0x12, 0x41, 0x72, 0x65, 0x59, 0x6f, 0x75, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x37, 0x0a, 0x11, 0x41, 0x72, 0x65, 0x59, 0x6f, 0x75, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x61, 0x79, 0x4f, 0x66, 0x54, 0x68, 0x65,
	0x57, 0x65, 0x65, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x61, 0x79, 0x4f,
	0x66, 0x54, 0x68, 0x65, 0x57, 0x65, 0x65, 0x6b, 0x22, 0x51, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x24, 0x0a, 0x05, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x05,
	0x64, 0x6f, 0x6e, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x30, 0x0a, 0x14, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x16, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x6e, 0x75,
	0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26,
	0x0a, 0x06, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x06,
	0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x22, 0x5d, 0x0a, 0x12, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44,
	0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x6f,
	0x6e, 0x75, 0x74, 0x73, 0x2e, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x43, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x13, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x6f,
	0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x51, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x24, 0x0a, 0x05, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x05,
	0x64, 0x6f, 0x6e, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2f, 0x0a, 0x13, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x0a, 0x12,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x49, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x49, 0x64, 0x73, 0x22, 0x31,
	0x0a, 0x13, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xd3, 0x03, 0x0a, 0x0d, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x41, 0x72, 0x65, 0x59, 0x6f, 0x75, 0x4f, 0x70, 0x65,
	0x6e, 0x12, 0x19, 0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x41, 0x72, 0x65, 0x59, 0x6f,
	0x75, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x64,
	0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x41, 0x72, 0x65, 0x59, 0x6f, 0x75, 0x4f, 0x70, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x64, 0x6f, 0x6e,
	0x75, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x6f,
	0x6e, 0x75, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4a, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x75, 0x74,
	0x73, 0x12, 0x1b, 0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f,
	0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a,
	0x0b, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x64,
	0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x44, 0x6f, 0x6e, 0x75, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x6f, 0x6e, 0x75, 0x74,
	0x73, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_donuts_protos_donuts_proto_rawDescOnce sync.Once
	file_donuts_protos_donuts_proto_rawDescData = file_donuts_protos_donuts_proto_rawDesc
)

func file_donuts_protos_donuts_proto_rawDescGZIP() []byte {
	file_donuts_protos_donuts_proto_rawDescOnce.Do(func() {
		file_donuts_protos_donuts_proto_rawDescData = protoimpl.X.CompressGZIP(file_donuts_protos_donuts_proto_rawDescData)
	})
	return file_donuts_protos_donuts_proto_rawDescData
}

var file_donuts_protos_donuts_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_donuts_protos_donuts_proto_goTypes = []interface{}{
	(*Donuts)(nil),                // 0: donuts.Donuts
	(*DonutsOrder)(nil),           // 1: donuts.DonutsOrder
	(*AreYouOpenResponse)(nil),    // 2: donuts.AreYouOpenResponse
	(*AreYouOpenRequest)(nil),     // 3: donuts.AreYouOpenRequest
	(*CreateDonutsRequest)(nil),   // 4: donuts.CreateDonutsRequest
	(*CreateDonutsResponse)(nil),  // 5: donuts.CreateDonutsResponse
	(*GetDonutsListRequest)(nil),  // 6: donuts.GetDonutsListRequest
	(*GetDonutsListResponse)(nil), // 7: donuts.GetDonutsListResponse
	(*OrderDonutsRequest)(nil),    // 8: donuts.OrderDonutsRequest
	(*OrderDonutsResponse)(nil),   // 9: donuts.OrderDonutsResponse
	(*UpdateDonutsRequest)(nil),   // 10: donuts.UpdateDonutsRequest
	(*UpdateDonutsReponse)(nil),   // 11: donuts.UpdateDonutsReponse
	(*ClearDonutsRequest)(nil),    // 12: donuts.ClearDonutsRequest
	(*ClearDonutsResponse)(nil),   // 13: donuts.ClearDonutsResponse
}
var file_donuts_protos_donuts_proto_depIdxs = []int32{
	0,  // 0: donuts.DonutsOrder.donut:type_name -> donuts.Donuts
	0,  // 1: donuts.CreateDonutsRequest.donut:type_name -> donuts.Donuts
	0,  // 2: donuts.GetDonutsListResponse.donuts:type_name -> donuts.Donuts
	1,  // 3: donuts.OrderDonutsRequest.order:type_name -> donuts.DonutsOrder
	0,  // 4: donuts.UpdateDonutsRequest.donut:type_name -> donuts.Donuts
	3,  // 5: donuts.DonutsService.AreYouOpen:input_type -> donuts.AreYouOpenRequest
	4,  // 6: donuts.DonutsService.CreateDonuts:input_type -> donuts.CreateDonutsRequest
	6,  // 7: donuts.DonutsService.GetDonutsList:input_type -> donuts.GetDonutsListRequest
	8,  // 8: donuts.DonutsService.OrderDonuts:input_type -> donuts.OrderDonutsRequest
	10, // 9: donuts.DonutsService.UpdateDonuts:input_type -> donuts.UpdateDonutsRequest
	12, // 10: donuts.DonutsService.ClearDonuts:input_type -> donuts.ClearDonutsRequest
	2,  // 11: donuts.DonutsService.AreYouOpen:output_type -> donuts.AreYouOpenResponse
	5,  // 12: donuts.DonutsService.CreateDonuts:output_type -> donuts.CreateDonutsResponse
	7,  // 13: donuts.DonutsService.GetDonutsList:output_type -> donuts.GetDonutsListResponse
	9,  // 14: donuts.DonutsService.OrderDonuts:output_type -> donuts.OrderDonutsResponse
	11, // 15: donuts.DonutsService.UpdateDonuts:output_type -> donuts.UpdateDonutsReponse
	13, // 16: donuts.DonutsService.ClearDonuts:output_type -> donuts.ClearDonutsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_donuts_protos_donuts_proto_init() }
func file_donuts_protos_donuts_proto_init() {
	if File_donuts_protos_donuts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_donuts_protos_donuts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Donuts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DonutsOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreYouOpenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreYouOpenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDonutsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDonutsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDonutsListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDonutsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDonutsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDonutsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDonutsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDonutsReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearDonutsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_donuts_protos_donuts_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearDonutsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_donuts_protos_donuts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_donuts_protos_donuts_proto_goTypes,
		DependencyIndexes: file_donuts_protos_donuts_proto_depIdxs,
		MessageInfos:      file_donuts_protos_donuts_proto_msgTypes,
	}.Build()
	File_donuts_protos_donuts_proto = out.File
	file_donuts_protos_donuts_proto_rawDesc = nil
	file_donuts_protos_donuts_proto_goTypes = nil
	file_donuts_protos_donuts_proto_depIdxs = nil
}
